const TOKEN_COOKIE_SESSION_NAME = "oauth_session";
const SESSION_EXPIRY_MILLISECONDS = 1000 * 60 * 60 * 24 * 30; //30 days
const ACTIVITY_CHECK_INTERVAL_MILLISECONDS = 1000 * 60 * 60 * 3; // 3 hours
const INACTIVITY_TIMEOUT_MILLISECONDS = 1000 * 60 * 60; // 1 hour

export {
  ACTIVITY_CHECK_INTERVAL_MILLISECONDS,
  INACTIVITY_TIMEOUT_MILLISECONDS,
  SESSION_EXPIRY_MILLISECONDS,
  TOKEN_COOKIE_SESSION_NAME,
};
